CREATE TABLE "nobels_laureates" (
  "id" int PRIMARY KEY,
  "year" varchar NOT NULL,
  "category" varchar NOT NULL,
  "prize" varchar NOT NULL,
  "motivation" varchar,
  "prize_share" varchar NOT NULL,
  "laureate_id" int NOT NULL,
  "laureate_type" varchar NOT NULL,
  "laureates_full_name" varchar NOT NULL,
  "laureates_birth_date" varchar NOT NULL,
  "laureates_birth_city" varchar NOT NULL,
  "accent_city" varchar NOT NULL,
  "city_region" int NOT NULL,
  "city_population" float,
  "city_latitude" float NOT NULL,
  "city_longitude" float NOT NULL,
  "country_name" varchar NOT NULL,
  "continent" varchar NOT NULL,
  "currency" varchar NOT NULL,
  "iso3" varchar NOT NULL,
  "phone_code" varchar NOT NULL,
  "country_population" int NOT NULL,
  "country_area_sq_mi" int NOT NULL,
  "country_pop_density" float NOT NULL,
  "country_coastline" float NOT NULL,
  "country_net_migration" float NOT NULL,
  "country_infant_mortality" float NOT NULL,
  "country_gdp_usd_per_capita" int NOT NULL,
  "country_literacy_percent" float NOT NULL
);
